title: vita-project
description: Central information hub for Project VITA
github_username: norrisaftcc
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
